www/protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{

    public function init() {
        // filter out garbage requests
        $uri = Yii::app()->request->requestUri;
        if (strpos($uri, 'favicon') || strpos($uri, 'robots')) {
            $this->redirect(Yii::app()->request->baseUrl.'/site/index');
        }
    }

    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'list' and 'show' actions
                'actions'=>array('index','logout','images','uploads','thumbs','hadleExcelAjax'),
                'users'=>array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions'=>array('entry','out','index','cancel','sale','excel','report','search','AjaxCodeChecker','AjaxOutCheck','edit','DeletePicture','hadleExcelAjax'),
                'expression' => 'Yii::app()->session[\'role\'] == "admin"',
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions'=>array('index','sale','cancel','satisRapor','entry','AjaxCodeChecker','search','AjaxOutCheck','edit','DeletePicture'),
                'expression' => 'Yii::app()->session[\'role\'] == "store"',
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    public function filters()
    {
        return array(
            'accessControl',
        );
    }

    public function actionCancel() {
        $model=new EntryForm;
        $saleObj = array();
        $err = false;
        $success = false;
        if (isset($_GET['sale_id'])) {
            $saleModel = new Sale;
            $saleObj = $saleModel->findByPk($_GET['sale_id']);
            if (!isset($saleObj->id)) {
                $err = 'not_found';
            } else if ($saleObj->store_id != $_SESSION['store']) {
                $err = 'other_store';
                unset($saleObj);
                $saleObj = array();
            }
            // satis iptali
            if ($err == false && $saleObj->status == 1 && isset($_GET['cancel']) && $_GET['cancel'] == 1) {
                $productInfo = EntryForm::model()->findProductByCode($saleObj->code);
                $saleModel->updateByPk($saleObj->id,array("status"=> -1 ));
                $saleObj = $saleModel->findByPk($_GET['sale_id']);
                $INV = new Inventory;
                if ($inventoryObj = $INV->findInventoryByProductIDstoreID($productInfo->id,$saleObj->store_id)) {
                    $INV->updateByPk($inventoryObj->id,array("quantity"=> $inventoryObj->quantity - 1));
                }
                $success = true;
            } else if ($err == false && $saleObj->status == -1 && isset($_GET['cancel']) && $_GET['cancel'] == -1) {
                // iptalin iptali
                $productInfo = EntryForm::model()->findProductByCode($saleObj->code);
                $saleModel->updateByPk($saleObj->id,array("status"=> 1 ));
                $saleObj = $saleModel->findByPk($_GET['sale_id']);
                $INV = new Inventory;
                if ($inventoryObj = $INV->findInventoryByProductIDstoreID($productInfo->id,$saleObj->store_id)) {
                    $INV->updateByPk($inventoryObj->id,array("quantity"=> $inventoryObj->quantity + 1));
                }
                $success = true;
            }

        }
        $this->render('cancel',array('model'=>$model,'saleObj'=>$saleObj,'err'=>$err, 'success' => $success));

    }
    public function actionSale() {
        $success = false;
        $productQntErrString = '';
        $uniqueBasketValue = md5(date('YmdHis'));
        if (isset($_POST['product_code']) && isset($_POST['pcode'])) {

            // Check if submited product quantites in store inventory
            $productQuantityError = array();
            $productQuantity = array();

            foreach ($_POST['pcode'] as $index => $val ) {
                $productObj =  EntryForm::model()->findProductByCode($val);
                $inventoryModel = new Inventory;
                $productInventory = $inventoryModel->find('product_id=:product_id and store_id=:store_id', array(':product_id'=>$productObj['id'],':store_id'=>Yii::app()->session['store']));

                if (isset($productInventory->quantity) && $productInventory->quantity > 0) {
                    $productQuantity[$productObj->code] = isset($productQuantity[$productObj->code])?$productQuantity[$productObj->code] + 1:1;
                }
                if ($productQuantity[$productObj->code] > $productInventory->quantity) {
                    $productQuantityError[$productObj->code] = $productInventory->quantity;
                }
            }

            if (!count($productQuantityError) > 0) {
                $total = 0;
                foreach ($_POST['pcode'] as $index => $val ) {
                    $productObj =  EntryForm::model()->findProductByCode($val);
                    $inventoryModel = new Inventory;
                    $productInventory = $inventoryModel->find('product_id=:product_id and store_id=:store_id', array(':product_id'=>$productObj['id'],':store_id'=>Yii::app()->session['store']));

                    if (isset($productInventory->quantity) && $productInventory->quantity > 0) {
                        $productInventory->product_id = $productObj->id;
                        $productInventory->quantity = ($productInventory->quantity - 1);
                        $productInventory->save();
                    } else {
                        continue;
                    }
                    $saleModel = new Sale;
                    $saleModel->code = $val;
                    $saleModel->product_category = $productObj->category_id;
                    $saleModel->price = $_POST['price'][$index];
                    $saleModel->payment = $_POST['paymentMethod'];
                    $saleModel->personel_id = $_POST['personelID'];
                    $saleModel->store_id = Yii::app()->session['store'];
                    $saleModel->discount = 0;
                    $saleModel->basket_id = $uniqueBasketValue;
                    $saleModel->idate = date("Y-m-d H:i:s");
                    if ($saleModel->save()) {
                        $total = $total + $_POST['price'][$index];
                        $success = true;
                    } else {
                        $success = -1;
                    }
                }
                if ($success == true && $total >= 100) {
                    $PUSH = new PushNotifications;
                    $Store = new Store;
                    $storeObj = $Store->findAllByAttributes(array('type'=>1,'id'=>Yii::app()->session['store']));
                    $PUSH->pushNotification("QQ - ".$storeObj[0]->name,$total." TL");
                }
            } else {
                foreach ($productQuantityError as $code => $qnt) {
                    // TODO LOG here
                    $productQntErrString .= 'Ürün: ' . $code .' Toplam Adet: '.$qnt.'<br>';
                }
            }
        }

        $saleModel = new Sale;
        $storePersonel = new StorePersonel;
        $storePersonelObj = $storePersonel->findAllByAttributes(array('store_id'=>Yii::app()->session['store']));
        $this->render('sale',array('model'=>$saleModel, 'success' => $success,'productQntErrString'=>$productQntErrString,'storePersonel'=>$storePersonelObj));
    }


	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
		// renders the view file 'protected/views/site/index.php'
		// using the default layout 'protected/views/layouts/main.php'
		//$this->render('index');

        if (Yii::app()->user->id) {
            $this->render('index',array('login'=>true));
            exit;
        }

        $model=new LoginForm;

        // if it is ajax validation request
        if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
        {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }

        // collect user input data
        if(isset($_POST['LoginForm']))
        {
            $model->attributes=$_POST['LoginForm'];
            // validate user input and redirect to the previous page if valid
            if($model->validate() && $model->login()) {
                $this->redirect(Yii::app()->user->returnUrl);
            }
        }

        $this->render('index',array('model'=>$model,'login'=>false));
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

    public function actionEdit() {

        $model = EntryForm::model()->findByPk($_GET['product_id']);


        $photo = new Photo;
        $success_code = '';

        if(isset($_POST['EntryForm'])) {
            $model->attributes = $_POST['EntryForm'];
            $model->category_id = $_POST['EntryForm']['category_id'];
            $model->code = $_POST['EntryForm']['code'];
            $model->title = $_POST['EntryForm']['title'];
            $model->description = $_POST['EntryForm']['description'];
            if (!isset($_POST['EntryForm']['buy_price']) || empty($_POST['EntryForm']['buy_price'])) {
                $model->buy_price = 0.00;
            } else {
                $model->buy_price = $_POST['EntryForm']['buy_price'];
            }
            if (!isset($_POST['EntryForm']['sale_price1']) || empty($_POST['EntryForm']['sale_price1'])) {
                $model->sale_price1 = 0.00;
            } else {
                $model->sale_price1 = $_POST['EntryForm']['sale_price1'];
            }

www/protected/views/site/cancel.php
<?php

if (!isset(Yii::app()->session['store']) && Yii::app()->session['role'] == 'admin') {
    echo "Admin olarak bir mağazadan satış iptali yapamazsınız.<br/>";
    echo '<a href="/site/index">Ana Sayfa</a><br/>';
    echo '<a href="/site/logout">logout</a><br/>';
    exit;
}
/*
if (strlen($productQntErrString) > 0) {
    ?><script type="text/javascript">toastr.error('Mağaza Stoğundan Olan Ürün sayısından fazlası satılmak istendi. Tüm satışlar iptal edildi. Stok Bilgisi: <br> <?php echo $productQntErrString;?>');</script><?php
} else if (isset($success) && $success == true) {?>
    <script type="text/javascript">toastr.success('Satış Kaydedildi  ');</script>
    <?php
} else if ($success == -1) {
    ?><script type="text/javascript">toastr.error('Satış Kaydedilmedi. Hata oluştu');</script><?php
}
*/
$form=$this->beginWidget('CActiveForm', array(
    'id'=>'entry-form',
    'enableClientValidation'=>true,
    'method'=>'get',
    'action' => '/site/cancel',
    'clientOptions'=>array(
        'validateOnSubmit'=>true,
    ),
    'focus'=>array($model,'sale_id'),
    'htmlOptions'=>array(
        //'onSubmit'=>'return false',
    ),
));
?>

    <div class="offset4">
        <div id="dcode" class="control-group">
            <?php echo $form->labelEx($model,'Satış Id'); ?>
            <?php echo $form->textField($model,'sale_id',array('name'=>'sale_id','value'=>isset($_GET['sale_id'])? $_GET['sale_id'] :'', 'style'=>'height:50px;')); ?>
            <span class="icon-large icon-barcode"></span>
        </div>
    </div> <!-- .span8 -->
<?php if (isset($saleObj->id)) {?>
    <div class="bs-example divider">
        <table class="table">
            <thead>
            <tr>
                <th colspan="5" style="text-align: center;background-color: #bdccff;">Satış Bilgisi</th>
            </tr>
            <tr>
                <th>ID</th>
                <th>Ürün Kodu</th>
                <th>Fiyat</th>
                <th>Satış Durumu</th>
                <th>Tarih</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td><?php echo $saleObj->id;?></td>
                <td><?php echo $saleObj->code;?></td>
                <td><?php echo $saleObj->price?></td>
                <td><?php echo $saleObj->status == 1?'Satış Başarılı':'İptal Edilmiş';?></td>
                <td><?php echo $saleObj->idate?></td>
            </tr>
            <tr>
                <td colspan="5" style="text-align: center">
                    <input type="hidden" name="cancel" value="<?php echo $saleObj->status == 1?'1':'-1';?>">
                    <button  type="submit" class="btn btn-<?php echo $saleObj->status == 1?'danger':'success';?> btn-large"><?php echo $saleObj->status == 1?'İPTAL ET':'AKTİF SATIŞ YAP';?></button></td>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
<?php }?>
<?php if (isset($err) && $err == 'other_store') { ?>
    <script>toastr.error('Başka Mağaza Satışı.');</script>
<?php } elseif (isset($err) && $err == 'not_found') { ?>
    <script>toastr.error('Satış ID Bulunamadı.');</script>
<?php } ?>
<?php if (isset($success) &&  $success == true && $saleObj->status == -1) { ?>
    <script>toastr.success('Satış İptal Edildi.');</script>
<?php }else if (isset($success) &&  $success == true && $saleObj->status == 1) { ?>
    <script>toastr.success('Satış Aktif Yapıldı.');</script>
<?php } ?>
<?php $this->endWidget();

www/protected/views/site/contact.php
<?php
/* @var $this SiteController */
/* @var $model ContactForm */
/* @var $form CActiveForm */

$this->pageTitle=Yii::app()->name . ' - Contact Us';
$this->breadcrumbs=array(
	'Contact',
);
?>

<h1>Contact Us</h1>

<?php if(Yii::app()->user->hasFlash('contact')): ?>

<div class="flash-success">
	<?php echo Yii::app()->user->getFlash('contact'); ?>
</div>

<?php else: ?>

<p>
If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
</p>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'contact-form',
	'enableClientValidation'=>true,
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name'); ?>
		<?php echo $form->error($model,'name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'email'); ?>
		<?php echo $form->textField($model,'email'); ?>
		<?php echo $form->error($model,'email'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'subject'); ?>
		<?php echo $form->textField($model,'subject',array('size'=>60,'maxlength'=>128)); ?>
		<?php echo $form->error($model,'subject'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'body'); ?>
		<?php echo $form->textArea($model,'body',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'body'); ?>
	</div>

	<?php if(CCaptcha::checkRequirements()): ?>
	<div class="row">
		<?php echo $form->labelEx($model,'verifyCode'); ?>
		<div>
		<?php $this->widget('CCaptcha'); ?>
		<?php echo $form->textField($model,'verifyCode'); ?>
		</div>
		<div class="hint">Please enter the letters as they are shown in the image above.
		<br/>Letters are not case-sensitive.</div>
		<?php echo $form->error($model,'verifyCode'); ?>
	</div>
	<?php endif; ?>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Submit'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

<?php endif; ?>

www/protected/views/site/error.php
<?php
/* @var $this SiteController */
/* @var $error array */

$this->pageTitle=Yii::app()->name . ' - Error';
$this->breadcrumbs=array(
	'Error',
);
?>

<?php echo $code; ?></h2>

<div class="error">
<?php echo CHtml::encode($message); ?>
</div>

?>
<style>
    .center {text-align: center; margin-left: auto; margin-right: auto; margin-bottom: auto; margin-top: auto;}
</style>
<title>Error 404</title>
<body>
<div class="hero-unit center">
    <h1>Page Not Found <small><font face="Tahoma" color="red">Error 404</font></small></h1>
    <br />
    <p>The page you requested could not be found, either contact your webmaster or try again. Use your browsers <b>Back</b> button to navigate to the page you have prevously come from</p>
    <p><b>Or you could just press this neat little button:</b></p>
    <a href="/" class="btn btn-large btn-info"><i class="icon-home icon-white"></i> Take Me Home</a>
</div>

www/protected/views/site/excel.php
<?php
$form=$this->beginWidget('CActiveForm', array(
    'id'=>'ff',
    'method'=>'get',
    'action' => '/site/excel'
));
?>
<div class="row">
    <div class="span-8">
        <?php echo $form->labelEx($model,'Kategori'); ?>
        <?php
        $selections = array(
            'all' => 'Tüm Ürünler',
            '1' => 'Kolye',
            '2' => 'Küpe',
            '3' => 'Bileklik',
            '4' => 'Yüzük',
            '5' => 'Çanta',
            '6' => 'Cüzdan',
            '7' => 'Hediyelik',
            '8' => 'Şal',

        );
        ?>
            <?php echo $form->dropDownList($model, 'category_id', $selections,array('name'=>'category_id','all' => 'Tüm Ürünler',
                'options' => isset($params['category_id'])?array($params['category_id']=>array('selected'=>true)):''));?>
    </div>
    <div class="span-8 last">
        <?php echo $form->labelEx($model,'Ürün Kodu'); ?>
        <?php echo $form->textField($model,'title',array('name'=>'code','value'=>isset($params['code'])? $params['code'] :'')); ?>
        &nbsp;&nbsp;&nbsp;<span style="vertical-align: top"> <button type="submit" class="btn btn-primary btn-small">Filtrele</button></span>
    </div>

</div>

<?php $this->endWidget();

$this->widget('ext.htmlTableUi.htmlTableUi',array(
    'ajaxUrl'=>'site/hadleExcelAjax',
    'arProvider'=>'',
    'collapsed'=>false,
    'columns'=>$columnsArray,
    'cssFile'=>'',
    'editable'=>true,
    'enableSort'=>true,
    'exportUrl'=>'site/exportTable',
    'extra'=>'İşlemler:',
    'footer'=> 'Sayfa: '. $currentPage.'/'.$totalPageCount . '<br/> Toplam Ürün: ' . $params['totalFound'],
    'formTitle'=>'Düzenle',
    'rows'=>$rowsArray,
    'sortColumn'=>1,
    'sortOrder'=>'desc',
    'title'=>'Femaly Accessories',
    'subtitle'=>'Ürün Listesi',
));


unset($_GET['sf']);
$reqUri = http_build_query($_GET);
if (strlen($reqUri) > 1) {
    $reqUri = '?'.$reqUri;
}

$reqUri .= $reqUri? '&':'?';

?>

<div class="text-center">
    <ul class="pager">
        <?php
        for($i = 1; $i <= $totalPageCount; $i++ ) {
            if ($i == 1) {
                if ($currentPage == 1) {
                    echo '<li class="disabled"><span>&laquo;</span></li>';
                } else {
                    echo '<li><a href="'.$reqUri.'sf='.($currentPage - 1).'">&laquo;</a></li>';
                }
            }

            if ($i == $currentPage) {
                echo '<li class="active"><span>'.$i.'</span></li>';
            } else {
                echo '<li><a href="'.$reqUri.'sf='.$i.'">'.$i.'</a></li>';
            }

            if ($i == $totalPageCount) {
                if ($currentPage == $i) {
                    echo '<li class="disabled"><span>&raquo;</span></li>';
            } else {
                    echo '<li><a href="'.$reqUri.'sf='.($currentPage + 1).'">&raquo;</a></li>';
                }
            }
        }
        ?>
    </ul>
</div>

www/protected/views/site/product_entry.php
<?php


$form=$this->beginWidget('CActiveForm', array(
    'id'=>'entry-form',
    'enableClientValidation'=>true,
    'clientOptions'=>array(
        'validateOnSubmit'=>true,
    ),
    'htmlOptions'=>array(
        'class'=>'span7',
        'enctype' => 'multipart/form-data',
    ),
));
?>

<div class="controls-row" xmlns="http://www.w3.org/1999/html">
    <div class="span6">
        <form action="" method="post" class="form-horizontal" id="product_form" accept-charset="utf-8">
            <?php

            if ($success_code) {
                if (isset($edit)) {
                    ?><script>toastr.success('Ürün düzenlendi.');</script><?php
                } else {
                    ?> <script>toastr.success('Ürün kayıt edildi.');</script>
                <?php }?>
                <p><span class="label label-success"><?php echo $success_code?> - <?php if(isset($edit)) { echo 'Düzenlendi';} else {echo 'Kayıt edildi.';}?></span></p>
            <?php } ?>
                    <div class="control-group">
                        <?php echo $form->labelEx($model,'Kategori'); ?>
                        <?php echo $form->dropDownList($model, 'category_id', $allCategories ,array('empty' => '(Seçiniz)',
                            'options' => isset($productObj->category_id)?array($productObj->category_id=>array('selected'=>true)):'')); ?>
                        <?php echo $form->error($model,'category_id'); ?>

                    </div>
                <?php if (!isset($edit)) { ?>
                    <div class="control-group">
                        <?php echo $form->labelEx($storeModel,'Mağaza'); ?>
                        <?php echo $form->dropDownList($storeModel, 'id', $storeArr ,array('empty' => '(Seçiniz)',
                            'options' => isset($productObj->category_id)?array($productObj->category_id=>array('selected'=>true)):'')); ?>
                        <?php echo $form->error($storeModel,'id'); ?>

                    </div>
                <?php }?>

                <div id="dcode" class="control-group">
                    <?php echo $form->labelEx($model,'Ürün Kodu'); ?>
                    <?php echo $form->textField($model,'code',array('style'=>'height:50px;','value'=>isset($productObj->code)? $productObj->code :'',
                    'ajax' => array(
                        'type'=>'POST', //request type
                        'url'=>CController::createUrl('site/AjaxCodeChecker'), //url to call.
                        'success'=>'function(data){
                            if (data == 1) {
                                toastr.error(\'Bu urun kodu kullanimda\');
                            }
                         }'
                    ))); ?>
                    <span class="icon-large icon-barcode"></span>
                    <?php echo $form->error($model,'code'); ?>

                </div>

                <div class="control-group">
                    <?php echo $form->labelEx($model,'Başlık'); ?>
                    <?php echo $form->textField($model,'title',array('value'=>isset($productObj->title)? $productObj->title :'')); ?>
                    <?php echo $form->error($model,'title'); ?>
                </div>

                <div class="control-group">
                    <?php echo $form->labelEx($model,'Açıklama'); ?>
                    <?php echo $form->textArea($model,'description',array('rows'=>5,'value'=>isset($productObj->description)? $productObj->description :'')); ?>
                    <?php echo $form->error($model,'description'); ?>
                </div>

                <div class="control-group">
                    <?php echo $form->labelEx($model,'Alış Fiyatı'); ?>
                    <?php echo $form->textField($model,'buy_price',array('value'=>isset($productObj->buy_price)? $productObj->buy_price :'')); ?>
                    <?php echo $form->error($model,'buy_price'); ?>
                </div>

                <div class="control-group">
                    <?php echo $form->labelEx($model,'Satış Fiyatı 1'); ?>
                    <?php echo $form->textField($model,'sale_price1',array('value'=>isset($productObj->sale_price1)? $productObj->sale_price1 :'')); ?>
                    <?php echo $form->error($model,'sale_price1'); ?>
                </div>

                <div class="control-group">
                    <?php echo $form->labelEx($model,'Satış Fiyatı 2'); ?>
                    <?php echo $form->textField($model,'sale_price2',array('value'=>isset($productObj->sale_price2)? $productObj->sale_price2 :'')); ?>
                    <?php echo $form->error($model,'sale_price2'); ?>
                </div>
                <?php if (!isset($edit)) { ?>
                <div class="control-group">
                    <?php echo $form->labelEx($model,'Adet'); ?>
                    <?php echo $form->textField($model,'quantity',array('value'=>isset($productObj->quantity)? $productObj->quantity :'1')); ?>
                    <?php echo $form->error($model,'quantity'); ?>
                </div>
                <?php }?>
                <div class="control-group">
                    <?php echo $form->labelEx($model,'Beden'); ?>
                    <?php echo $form->textField($model,'size',array('value'=>isset($productObj->size)? $productObj->size :'')); ?>
                    <?php echo $form->error($model,'size'); ?>
                </div>

                <div class="control-group">
                    <?php echo $form->labelEx($model,'Renk'); ?>
                    <?php echo $form->textField($model,'color',array('value'=>isset($productObj->color)? $productObj->color :'')); ?>
                    <?php echo $form->error($model,'color'); ?>
                </div>
                <div class="control-group">
                    <?php if (isset($photoArr['images']) && isset($edit)) {
                        foreach ($photoArr['images'] as $id => $img_url) {
                    ?>
                    <div style="margin:10px;float: left">
                    <img id="image_<?php echo $id;?>" class="media-object dp img-circle" src="<?php echo Yii::app()->request->baseUrl."/images/uploads/thumbs/".$img_url;?>" style="width: 100px;height:100px;">
                    <span style="display: block; text-align: center"><?php
                        echo CHtml::ajaxLink('Sil',Yii::app()->createUrl('site/DeletePicture',array('id'=>$id,'image'=>$img_url)),
                                array(
                                    'type'=>'POST',
                                    'data'=> 'js:$("#dataContainer").serialize()',
                                    'success'=>'js:function(res){
                                        if (res == -1) {
                                            toastr.error(\'Hata Oluştu.\');
                                        } else {
                                            $(\'#image_text_\'+res).hide();
                                            $(\'#image_\'+res).hide();
                                            toastr.success(\'Resim Silindi.\');
                                        }
                                     }'
                                ),array('id'=>'image_text_'.$id,));
                        ?>

                    </span>
                    </div>
                    <?php }}?>
                </div>
            <div class="control-group" style="clear: both">
                <input type="hidden" name="MAX_FILE_SIZE" value="5900000" />
                <input type="file" name="dosya[]" id="dosya[]" multiple="multiple" />
            </div>

            <div class="form-actions">
                <button type="submit" class="btn btn-large btn-primary"><?php echo isset($edit) ?'Ürün Düzenle':'Ürünü Kaydet';?></button>
            </div>
        </form>
    </div> <!-- .span6 -->
</div>

<?php if (isset($lastRow) && !empty($lastRow)) {
    $firstPhoto = '';
        if(isset($photoArr['images'])) {
            $firstPhoto = array_values($photoArr['images']);
            $firstPhoto = $firstPhoto[0];
        }
    ?>

    <a href="#" class="close"></a>
    <div class="row-fluid">
        <ul class="thumbnails">
            <li class="span3">
                <div class="thumbnail" style="padding: 0">
                    <div class="caption">
                        <p>Son Girilen Ürün<p>
                    </div>
                    <div style="padding:4px">
                        <img width="250" height="150" src="<?php echo !empty($firstPhoto)? Yii::app()->request->baseUrl."/images/uploads/thumbs/".$firstPhoto:'';?>">
                    </div>
                    <div class="caption">
                        <h2><?php echo $lastRow->code;?></h2>
                        <p><?php echo $lastRow->title;?></p>
                        <?php if (isset($lastRow->buy_price)) {?><p><i class="icon icon-tag"></i> <?php echo $lastRow->buy_price;?> TL</p><?php } ?>
                        <p><?php echo CHtml::link('Düzenle',array('site/edit','product_id'=>$lastRow->id)); ?></p>
                    </div>
                </div>
            </li>
        </ul>

    </div>

<?php }?>
<?php $this->endWidget();?>
<script>
    toastr.options = {
        "closeButton": true,
        "debug": false,
        "positionClass": "toast-top-full-width",
        "onclick": null,
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
    }
</script>

www/protected/views/site/report.php
<div class="span6">
    <h5>Ürün kategori dağılımı</h5>
    <?php foreach ($categoryCountArr as $catName => $val) {
        $percent = round(($val['count']/$total)*100);
        ?>
    <strong><?php echo $catName;?></strong><span class="pull-right"><?php echo $val['count'].' ('.$percent;?>%)</span>
    <div class="progress progress-success active">
        <div class="bar" style="width: <?php echo $percent;?>%;"></div>
    </div>
    <?php } ?>
</div>